src/models.py
from src import db
from sqlalchemy.orm import backref

class Roomplan(db.Model):
    __tablename__ = 'roomplan'

    name = db.Column(db.String, primary_key=True)
    width = db.Column(db.Integer, default=700)
    height = db.Column(db.Integer, default=500)
    tables = db.relationship('Tables', cascade='all,delete', backref='tables', lazy=True)
    walls = db.relationship('Walls', cascade='all,delete', backref='walls', lazy=True)


    def __init__(self, name):
        self.name = name


    def __repr__(self):
        return '<title {}'.format(self.name)



class Tables(db.Model):
    __tablename__ = 'tables'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, db.ForeignKey('roomplan.name'), nullable=False, primary_key=True)
    xpos = db.Column(db.Integer)
    ypos = db.Column(db.Integer)
    width = db.Column(db.Integer)
    height = db.Column(db.Integer)
    capacity = db.Column(db.Integer)



    def __init__(self, id, xpos,ypos,width, height,name,capacity):
        self.id = id
        self.xpos = xpos
        self.ypos = ypos
        self.width = width
        self.height = height
        self.name = name
        self.capacity = capacity


    def __repr__(self):
        return '<title {}'.format(self.name)


class Walls(db.Model):
    __tablename__ = 'wall'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, db.ForeignKey('roomplan.name'), nullable=False, primary_key=True)
    x_start = db.Column(db.Integer)
    x_end = db.Column(db.Integer)
    y_start = db.Column(db.Integer)
    y_end= db.Column(db.Integer)

    def __init__(self, id, name, x_start, x_end, y_start, y_end):
        self.id = id
        self.name = name
        self.x_start = x_start
        self.y_start = y_start
        self.x_end = x_end
        self.y_end = y_end


    def __repr__(self):
        return '<title {}'.format(self.name)

src/__init__.py
from flask_sqlalchemy import SQLAlchemy
import os
from flask import Flask


def get_env_variable(name):
    try:
        return os.environ[name]
    except KeyError:
        message = "Expected environment variable '{}' not set.".format(name)
        raise Exception(message)


# Henter inn environment variablene for å sette opp Postgres databse
POSTGRES_URL = get_env_variable("POSTGRES_URL")
POSTGRES_USER = get_env_variable("POSTGRES_USER")
POSTGRES_PW = get_env_variable("POSTGRES_PW")
POSTGRES_DB = get_env_variable("POSTGRES_DB")
DB_URL = 'postgresql+psycopg2://{user}:{pw}@{url}/{db}'.format(user=POSTGRES_USER,pw=POSTGRES_PW,url=POSTGRES_URL,db=POSTGRES_DB)



app = Flask(__name__, instance_relative_config=True)
app.config['SQLALCHEMY_DATABASE_URI'] = DB_URL
app.config.from_object(os.environ['APP_SETTINGS'])
db = SQLAlchemy(app)


####################
#### blueprints ####
####################

from src.views.admin import admin_blueprint
from src.views.user import user_blueprint

# register the blueprints
app.register_blueprint(admin_blueprint)
app.register_blueprint(user_blueprint)

src/app.py
from __init__ import app


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=80)

src/views/admin.py
from flask import Flask, render_template, Blueprint, request, redirect, url_for, session, jsonify
from src import app, db
from src.models import Roomplan
import json
import requests
from src.get_functions import *
from src.insert_functions import *
from src.update_functions import *
from src.delete_functions import *


admin_blueprint = Blueprint('admin', __name__)


@admin_blueprint.route('/update', methods=['POST'])
def update():
    if request.method == 'POST':
        data = request.get_json()
        table_name = session.get('admin-roomplan')
        return update_roomplan(table_name, data)


@admin_blueprint.route('/add', methods=['POST'])
def add():
    if request.method == 'POST':
        data = request.get_json()
        table_name = data["name"]
        response = get_db_status(table_name, data)
        if response["status"] == "error":
            print(response)
            return json.dumps(response)
        
        insert_roomplan(table_name.lower(),data)
        session["admin-roomplan"] = table_name
        message = {
            "status": "success",
            "message": "Successfully added to database"
        }
        return json.dumps(message)


@admin_blueprint.route('/delete', methods=['POST'])
def delete():
    if request.method == 'POST':
        deleted_table = request.form.get("deletedname")
        delete_roomplan(deleted_table)
        return redirect("/admin")
    else:
        return redirect("/admin")



@admin_blueprint.route('/clear/session', methods=['GET'])
def clear():
    if request.method == 'GET':
        session.clear()
        return redirect('/admin')
    else:
        return redirect('/admin')


@admin_blueprint.route('/admin')
def admin():
    session.pop('user-roomplan', None)
    restaurant_list = get_restaurants()
    if 'admin-roomplan' in session:
        sessionResponse = session.get('admin-roomplan')
        return render_template("admin.html", restaurants=restaurant_list, session=sessionResponse)
    else:
        return render_template("admin.html", restaurants=restaurant_list, newroomplan="ok")


# Denne kalles fra html når man ønsker laste inn et eksisterende bordoppsett
# Setter session lik restauranten de valgte og redirecter til /admin som vil håndtere det å vise bordoppsettet
@admin_blueprint.route('/load/admin', methods=['POST'])
def load():
    if request.method == 'POST':
        restaurant = request.form.get("restaurants")
        print(restaurant)
        session['admin-roomplan'] = restaurant
        return redirect("/admin")
    else:
        return redirect("/admin")


@admin_blueprint.route('/search', methods=['POST'])
def search():
    if request.method == 'POST':
        session.clear()
        search = request.form.get("search").lower()
        restaurants = get_restaurants()
        if search in restaurants:
            session['admin-roomplan'] = search
    return redirect("/admin")    


# Bare en route for å vise json fil til hvert bordopsett
@admin_blueprint.route('/api/<tablename>')
def api(tablename):
    return get_json_setup(tablename)

@admin_blueprint.route('/api/restaurants')
def restaurants():
    restaurants = get_restaurants()
    return json.dumps(restaurants)


@admin_blueprint.route('/load/json')
def loadjson():
    if 'user-roomplan' in session:
        return get_json_setup(session['user-roomplan'])
    if 'admin-roomplan' in session:
        return get_json_setup(session['admin-roomplan'])
    else:
        return get_json_setup("basic")

src/views/user.py
from flask import Flask, render_template, Blueprint, request, redirect, url_for, session, jsonify
from src import app, db
from src.models import Roomplan
import json
import requests
from src.get_functions import *
from src.insert_functions import *
from src.update_functions import *
from flask import Response
from flask import request
user_blueprint = Blueprint('user', __name__)

@user_blueprint.route('/')
def index():
    return redirect("/table/oslo")

@user_blueprint.route('/test')
def testing():
    return render_template("test.html")

@user_blueprint.route('/table/<tablename>')
def table(tablename):
    session.pop('admin-roomplan', None)
    session['user-roomplan'] = tablename
    return render_template("index.html")

@user_blueprint.route('/api/booking/posttables', methods=['POST'])
def ourAPItest():
    d = request.get_json()
    t = requests.post('https://jsonplaceholder.typicode.com/posts', json=d)
    return Response(t, status=200)

@user_blueprint.route('/api/booking/<restname>')
def apiTest(restname):
    data = {"tables": [1, 4], "nrOfPeople": 3, "name": restname}
    return json.dumps(data)

src/templates/admin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TableVisTest</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="/static/app.js"></script>
    <script src="/static/visualizer.js"></script>
    <script src="/static/admin.js"></script>
    <link rel="stylesheet" href="/static/styleAdmin.css">
</head>

<body>

    <div class="container-fluid admin-panel">
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="/admin">ADMIN</a>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link nav-load" href="#">Load <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-new" href={{ url_for('admin.clear') }}>New</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Edit
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item nav-add-tables" href="#">Add tables</a>
                            <a class="dropdown-item nav-add-walls" href="#">Add walls</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Save
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item nav-update" href="#">Update current</a>
                            <a class="dropdown-item nav-save" href="#">Save as new </a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-delete" href="#">Delete</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0" action="{{ url_for('admin.search') }}" method="post">
                    <input id="myInput" class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>

        <div class="card-header text-center">
            {% if session %}
            <h2 display-4>{{session}}</h1>
            {% else %}
            <h2 display-4>Default</h1>
            {% endif %}
        </div>


        <div class="card card-load text-center card-body">
            <h5 class="card-title">Load a setup</h5>
            <form action="{{ url_for('admin.load') }}" method="post">
                <select name="restaurants" class="custom-select col-6" id="mydropdown">
                    <option value="Default">Select a restaurant</option>
                    {% for restaurant in restaurants %}
                    <option value={{restaurant}}>{{restaurant}}</option>
                    {% endfor %}
                </select>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            <hr>
        </div>




        {% if newroomplan %}
        <div class="card text-center card-new">

            <h5 class="card-title">Use the edit tools to add items on this restaurant</h5>

        </div>
        {% endif %}






        <div class="card text-center card-add-tables"></div>

        <div class="card-body card text-center card-add-tables">
            <h5 class="card-title">Add tables</h5>
            <hr>
            <div class="container-fluid add-fluid">
                <div class="row">
                    <div class="col-sm">
                        <h6 class="card-subtitle mb-2 text-muted">Customize size</h6>
                        <h6 class="card-subtitle mb-2">Width: <span><input type="text" id="table-width" value="200" size="5">
                        </span> Height: <span><input id="table-height" type="text" value="20" size="5"></span></h6>
                        <div id="resizable" class="ui-widget-content">
                        </div>
                    </div>
                    <div class="col-sm">
                        <h6 class="card-subtitle mb-2 text-muted">Number of people on this table</h6>
                        <select id="capacityList">
                            <option value="2">2</option>
                            <option value="4">4</option>
                            <option value="6">6</option>
                            <option value="8">8</option>
                            <option value="10">10</option>
                            <option value="12">12</option>
                            <option value="14">14</option>
                            <option value="16">16</option>
                            <option value="18">18</option>
                            <option value="20">20</option>
                        </select>
                    </div>
                    <div class="col-sm">
                        <h6 class="card-subtitle mb-2 text-muted">Add this table to the roomplan</h6>
                        <button type="submit" class="btn btn-primary" id="addBtn">Submit</button>
                    </div>
                </div>
                <hr>
            </div>
        </div>


        <div class="card text-center card-add-walls"></div>
        <div class="card-body card text-center card-add-walls">
            <h5 class="card-title wall-header">Draw your walls on this canvas </h5>
            <div class="col-md" id="myDivCanvas"><canvas id="myCanvas" width="700" height="500" > </canvas> </div>
            <hr>
            <div class="container-fluid add-fluid">
                <div class="row">
                    <div class="col-sm">
                        <h6 class="card-subtitle mb-2 text-muted">Add Walls to the roomplan</h6>
                        <div class="alert alert-warning" id="wall-add-warning">Not a valid position to click on</div>
                        <div class="alert alert-success" id="wall-add-success">Valid position! click to add</div>
                        <div class="alert alert-success" id="wall-add-status">Success! add the walls to the roomplan below</div>
                        <button type="submit" class="btn btn-primary" id="addWall">Submit</button>
                    </div>
                </div>
                <hr>
            </div>
        </div>        

        <div class="card card-update text-center ">
            <div class="card-body">
                {% if session %}
                <h5 class="card-title">Do you want to update the {{session}} roomplan?</h5>
                <a href="#" class="btn btn-primary" id="updateBtn">Yes</a>
                <div class="alert alert-info" id="update-response-text">
                </div>
                <hr>
            {% else %}
            <h5 class="card-title">This roomplan is not stored</h5>
            <hr>
            {% endif %}
        </div>
      </div>


    <div class="card card-save text-center ">
        <div class="card-body">
            <div class="form-group col-6">
                <label for="tableNameForm">Give this roomplan a name and click on the save button</label>
                <input type="text" class="form-control" id="tableNameForm" placeholder="Table name..">
            </div>
            <a href="#" class="btn btn-primary" id="saveBtn">Submit</a>
            <div class="alert alert-info" id="save-response-text">
            </div>
            <hr>
        </div>
    </div>
    


    <div class="card card-delete text-center ">
        <div class="card-body">
            <div class="form-group col-6">
                <form action="{{ url_for('admin.delete') }}" method="post">
                <label for="tableNameForm">Enter the name of roomplan you want to delete</label>
                <input type="text" class="form-control" name="deletedname" placeholder="Name of roomplan..">
            </div>
            <button  name="submit_button" type="submit" class="btn btn-primary">Delete roomplan</button>
          </form>
            <hr>
        </div>
      </div>
    
  </div>










    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet" />
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="/static/adminMenu.js"></script>

</body>

</html>

src/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TableVisTest</title>
    <link rel="stylesheet" href="/static/style.css">
    <script src="/static/app.js"></script>
    <script src="/static/visualizer.js"></script>
    <script src="/static/user.js"></script>
</head>
<body>
</body>
</html>